version: '2'
services:
  postgis:
    image: bde2020/postgis
    hostname: postgis
    ports:
      - "5432:5432"
  strabon:
    image: bde2020/strabon
    hostname: strabon
    ports:
      - "9999:8080"
    links:
      - "postgis:postgis"

